[package]
name = "movine-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
movine-core = { path = "../movine-core" }
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
